name: CI Pipeline

on:
  pull_request:
    branches:
      - main  # This runs when a PR is opened for the main branch

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # This checks out the repository

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"  

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have a `requirements.txt` file
      - name: Run Tests with Pytest
        run: pytest --maxfail=5 --disable-warnings --tb=short  # Let us run the tests

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy API
        run: | uvicorn main:app --host 0.0.0.0 --port 8000 &